# Generated by Django 4.1.5 on 2023-01-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.PositiveIntegerField()),
                ('cep', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=14)),
                ('pergunta', models.CharField(max_length=50)),
                ('resposta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('quarto', 'Quarto'), ('cozinha', 'Cozinha'), ('banheiro', 'Banheiro'), ('sala', 'Sala')], default='Quarto', max_length=30)),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('descricao', models.TextField(max_length=1000)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.usuario')),
            ],
        ),
    ]
