# Generated by Django 4.1.5 on 2023-01-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
