# Generated by Django 4.1.5 on 2023-01-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='perguta',
            new_name='pergunta',
        ),
    ]
