# Generated by Django 4.1.5 on 2023-01-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0002_rename_perguta_usuario_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
