# Generated by Django 4.1.5 on 2023-01-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_remove_produto_category_delete_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('quarto', 'Quarto'), ('cozinha', 'Cozinha'), ('banheiro', 'Banheiro'), ('sala', 'Sala')], default='Quarto', max_length=30),
        ),
    ]
